server:
  port: 8089
spring:
  datasource:
    url: jdbc:h2:~/movedata
    driver-class-name: org.h2.Driver
    username: admin
    password: 123456

  #    schema: classpath:db/schema.sql
  #    data: classpath:db/data.sql
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true

  #设置静态资源路径，多个以逗号分隔
  web:
    resources:
      static-locations: classpath:static/
  application:
    name: datamove
  thymeleaf:
    prefix: classpath:templates/
    cache: false

